Some Readme content edits
hellt/vrnetlab pull request #291
Opened 2024-12-06 21:36 UTC by mjbear

Overall some minor items in the Readme content.

* Fix typo(s)
* Replace a broken netdevops.me hyperlink with an archive.org copy of that page
* Move the Connection Mode list into a table

I'm open to feedback and any tweaks/changes.

2024-12-07 11:28 UTC, hellt requested changes
thanks @mjbear 
a couple of small additions

2024-12-07 11:28 UTC, hellt commented on README.md
> +> this [documentation entry](https://containerlab.srlinux.dev/manual/vrnetlab/)
```suggestion
> this [documentation entry](https://containerlab.dev/manual/vrnetlab/)
```

2024-12-07 11:28 UTC, hellt commented on README.md
> +[this post](https://web.archive.org/web/20220621131105/https://netdevops.me/2021/transparently-redirecting-packets/frames-between-interfaces/)
```suggestion
[this post](https://netdevops.me/2021/transparently-redirecting-packetsframes-between-interfaces/)
```

2024-12-07 13:08 UTC, mjbear commented
> thanks @mjbear a couple of small additions

Thank you @hellt
I'm going to give the documentation another read or two. I'll mark it as "Ready" when I have it ready for merging.
Thank you!

2024-12-07 21:52 UTC, mjbear commented
@hellt
Admittedly my take on some of the sentences and wording. Hopefully I didn't distort the intended information and message.

Just like your earlier suggestions, I'm open to them. :grinning:

2024-12-08 20:18 UTC, merged

2024-12-08 20:18 UTC, hellt commented
thank you

2024-12-08 23:55 UTC, mjbear commented
> thank you

Teamwork!
Thank you as well. :grinning: